const GET_NEW_RELEASE_START = 'GET_NEW_RELEASE_START';
const GET_NEW_RELEASE_SUCCESS = 'GET_NEW_RELEASE_SUCCESS';
const GET_NEW_RELEASE_FAILED = 'GET_NEW_RELEASE_FAILED';
const FORCE_UPDATE_NEW_RELEASE = 'FORCE_UPDATE_NEW_RELEASE';

export {
    GET_NEW_RELEASE_START,
    GET_NEW_RELEASE_SUCCESS,
    GET_NEW_RELEASE_FAILED,
    FORCE_UPDATE_NEW_RELEASE,
};
