const TOKEN = 'TOKEN';
const PORTAL_URL = 'PORTAL_URL';
const LEFT_MENU_KEY = 'LEFT_MENU_KEY';
const ARTIST_NAME = 'ARTIST_NAME';
const ARTIST_IMAGE_URL = 'ARTIST_IMAGE_URL';
const ARTIST_FANS = 'ARTIST_FANS';
const TRACK_ID = 'TRACK_ID';
const TRACK_URL = 'TRACK_URL';
const TRACK_IMAGE = 'TRACK_IMAGE';
const TRACK_NAME = 'TRACK_NAME';
const TRACK_SUBTITLE = 'TRACK_SUBTITLE';
const PLAY_VOLUME = 'PLAY_VOLUME';
const PLAYLIST = 'PLAYLIST';
const PLAYLIST_NAME = 'PLAYLIST_NAME';
const PLAYLIST_TOTAL = 'PLAYLIST_TOTAL';
const PLAYLIST_IMAGE = 'PLAYLIST_IMAGE';
const PLAYLIST_SOURCE = 'PLAYLIST_SOURCE';
const PAUSE_TIME = 'PAUSE_TIME';
const PROGRESS_BAR = 'PROGRESS_BAR';
const NEW_PROGRESS_TIME = 'NEW_PROGRESS_TIME';

export {
    TOKEN,
    PORTAL_URL,
    LEFT_MENU_KEY,
    ARTIST_NAME,
    ARTIST_IMAGE_URL,
    ARTIST_FANS,
    TRACK_ID,
    TRACK_URL,
    TRACK_IMAGE,
    TRACK_NAME,
    TRACK_SUBTITLE,
    PLAY_VOLUME,
    PLAYLIST,
    PLAYLIST_NAME,
    PLAYLIST_TOTAL,
    PLAYLIST_IMAGE,
    PLAYLIST_SOURCE,
    PAUSE_TIME,
    PROGRESS_BAR,
    NEW_PROGRESS_TIME
};
