const GET_ARTIST_DATA_START = 'GET_ARTIST_DATA_START';
const GET_ARTIST_DATA_SUCCESS = 'GET_ARTIST_DATA_SUCCESS';
const GET_ARTIST_DATA_FAILED = 'GET_ARTIST_DATA_FAILED';
const FORCE_UPDATE_ARTIST_DATA = 'FORCE_UPDATE_ARTIST_DATA';

const GET_ARTIST_TOP_TRACK_START = 'GET_ARTIST_TOP_TRACK_START';
const GET_ARTIST_TOP_TRACK_SUCCESS = 'GET_ARTIST_TOP_TRACK_SUCCESS';
const GET_ARTIST_TOP_TRACK_FAILED = 'GET_ARTIST_TOP_TRACK_FAILED';
const FORCE_UPDATE_TOP_TRACK = 'FORCE_UPDATE_TOP_TRACK';

const GET_ARTIST_ALBUM_START = 'GET_ARTIST_ALBUM_START';
const GET_ARTIST_ALBUM_SUCCESS = 'GET_ARTIST_ALBUM_SUCCESS';
const GET_ARTIST_ALBUM_FAILED = 'GET_ARTIST_ALBUM_FAILED';
const FORCE_UPDATE_ALBUM = 'FORCE_UPDATE_ALBUM';

export {
    GET_ARTIST_DATA_START,
    GET_ARTIST_DATA_SUCCESS,
    GET_ARTIST_DATA_FAILED,
    FORCE_UPDATE_ARTIST_DATA,
    GET_ARTIST_TOP_TRACK_START,
    GET_ARTIST_TOP_TRACK_SUCCESS,
    GET_ARTIST_TOP_TRACK_FAILED,
    FORCE_UPDATE_TOP_TRACK,
    GET_ARTIST_ALBUM_START,
    GET_ARTIST_ALBUM_SUCCESS,
    GET_ARTIST_ALBUM_FAILED,
    FORCE_UPDATE_ALBUM
};
