const SEARCH_START = 'SEARCH_START';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
const SEARCH_FAILED = 'SEARCH_FAILED';
const FORCE_UPDATE_SEARCH = 'FORCE_UPDATE_SEARCH';

export {
    SEARCH_START,
    SEARCH_SUCCESS,
    SEARCH_FAILED,
    FORCE_UPDATE_SEARCH,
};
