const GET_FEATURED_START = 'GET_FEATURED_START';
const GET_FEATURED_SUCCESS = 'GET_FEATURED_SUCCESS';
const GET_FEATURED_FAILED = 'GET_FEATURED_FAILED';
const FORCE_UPDATE_FEATURED = 'FORCE_UPDATE_FEATURED';

export {
    GET_FEATURED_START,
    GET_FEATURED_SUCCESS,
    GET_FEATURED_FAILED,
    FORCE_UPDATE_FEATURED,
};
