const AUDIO_NEW_PLAY = 'AUDIO_NEW_PLAY';
const AUDIO_PLAY = 'AUDIO_PLAY';
const AUDIO_STOP = 'AUDIO_STOP';
const AUDIO_PREV = 'AUDIO_PREV';
const AUDIO_NEXT = 'AUDIO_NEXT';
const AUDIO_ENDED = 'AUDIO_ENDED';
const UPDATE_VOLUME = 'UPDATE_VOLUME';
const UPDATE_PLAY_STATE = 'UPDATE_PLAY_STATE';
const UPDATE_PLAY_PROGRESS = 'UPDATE_PLAY_PROGRESS';
const FORCE_UPDATE_AUDIO = 'FORCE_UPDATE_AUDIO';

export {
    AUDIO_NEW_PLAY,
    AUDIO_PLAY,
    AUDIO_STOP,
    AUDIO_PREV,
    AUDIO_NEXT,
    AUDIO_ENDED,
    UPDATE_VOLUME,
    UPDATE_PLAY_STATE,
    UPDATE_PLAY_PROGRESS,
    FORCE_UPDATE_AUDIO
};
