const GET_ALBUM_PLAY_LIST_START = 'GET_ALBUM_PLAY_LIST_START';
const GET_ALBUM_PLAY_LIST_SUCCESS = 'GET_ALBUM_PLAY_LIST_SUCCESS';
const GET_ALBUM_PLAY_LIST_FAILED = 'GET_ALBUM_PLAY_LIST_FAILED';

const FORCE_UPDATE_ALBUM_PLAY_LIST = 'FORCE_UPDATE_ALBUM_PLAY_LIST';

export {
    GET_ALBUM_PLAY_LIST_START,
    GET_ALBUM_PLAY_LIST_SUCCESS,
    GET_ALBUM_PLAY_LIST_FAILED,
    FORCE_UPDATE_ALBUM_PLAY_LIST
};
