const GET_PLAY_LIST_START = 'GET_PLAY_LIST_START';
const GET_PLAY_LIST_SUCCESS = 'GET_PLAY_LIST_SUCCESS';
const GET_PLAY_LIST_FAILED = 'GET_PLAY_LIST_FAILED';
const FORCE_UPDATE_PLAY_LIST = 'FORCE_UPDATE_PLAY_LIST';

export {
    GET_PLAY_LIST_START,
    GET_PLAY_LIST_SUCCESS,
    GET_PLAY_LIST_FAILED,
    FORCE_UPDATE_PLAY_LIST,
};
