const GET_GENRES_START = 'GET_GENRES_START';
const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
const GET_GENRES_FAILED = 'GET_GENRES_FAILED';

const GET_GENRES_CONTENT_START = 'GET_GENRES_CONTENT_START';
const GET_GENRES_CONTENT_SUCCESS = 'GET_GENRES_CONTENT_SUCCESS';
const GET_GENRES_CONTENT_FAILED = 'GET_GENRES_CONTENT_FAILED';

const FORCE_UPDATE_GENRES = 'FORCE_UPDATE_GENRES';

export {
    GET_GENRES_START,
    GET_GENRES_SUCCESS,
    GET_GENRES_FAILED,
    GET_GENRES_CONTENT_START,
    GET_GENRES_CONTENT_SUCCESS,
    GET_GENRES_CONTENT_FAILED,
    FORCE_UPDATE_GENRES,
};
